import bold from './list/bold';
import italic from './list/italic';
import underline from './list/underline';
import justifycenter from './list/justifycenter';
import justifyfull from './list/justifyfull';
import justifyleft from './list/justifyleft';
import justifyright from './list/justifyright';
import inserthorizontalrule from './list/inserthorizontalrule';
import cut from './list/cut';
import copy from './list/copy';
import redo from './list/redo';
import undo from './list/undo';
import removeformat from './list/removeformat';
import insertunorderedlist from './list/insertunorderedlist';
import insertorderedlist from './list/insertorderedlist';
// import image from './list/image';
// import fontname from './list/fontname';
// import fontsize from './list/fontsize';
// import code from './list/code';
// import full from './list/full';
// import backcolor from './list/backcolor';
// import forecolor from './list/forecolor';
// import video from './list/video';
// import table from './list/table';
// import link from './list/link';
// import paste from './list/paste';
// import plainpaste from './list/plainpaste';
// import wordpaste from './list/wordpaste';
// import formatblock from './list/formatblock';
// import indent from './list/indent';
// import lineheight from './list/lineheight';

const list = Object.create(null);

list.bold = bold;
list.italic = italic;
list.underline = underline;
list.justifycenter = justifycenter;
list.justifyfull = justifyfull;
list.justifyleft = justifyleft;
list.justifyright = justifyright;
list.inserthorizontalrule = inserthorizontalrule;
list.cut = cut;
list.copy = copy;
list.redo = redo;
list.undo = undo;
list.removeformat = removeformat;
list.insertunorderedlist = insertunorderedlist;
list.insertorderedlist = insertorderedlist;
// list.image = image;
// list.fontname = fontname;
// list.fontsize = fontsize;
// list.code = code;
// list.full = full;
// list.backcolor = backcolor;
// list.forecolor = forecolor;
// list.video = video;
// list.table = table;
// list.link = link;
// list.paste = paste;
// list.plainpaste = plainpaste;
// list.wordpaste = wordpaste;
// list.formatblock = formatblock;
// list.indent = indent;
// list.lineheight = lineheight;

export default list;
